### ISSUE TITLE
Replace font

### ISSUE THREAD

**Issue by roaldarbol** [sneakers-the-rat/journal-rss#12]
The current one screams 1987 - there are some really nice ones on e.g. https://open-foundry.com/. 

Do folks have preferences whether we include a file in the repo, or get them through a CDN?

**Comment by sneakers-the-rat** [comment]
as much love as i have for `system default font`, hell ya. i'd prefer to vendor them as .woff/.woff2 vs. a CDN :). i'll come help with styles after i get the basic stuff working!

**Comment by sneakers-the-rat** [comment]
vanilla css has variables :)

```css
:root {
  --font-body: "Papyrus";
}

span {
  font-family: var(--font-body);
}

```
